### ISSUE TITLE
GL Parts list is incorrect

### ISSUE THREAD

**Issue by jasonycw** [IX-Xur/MHW-Shop-Editor#15]
There are some MR parts
![image](https://user-images.githubusercontent.com/4518597/80283443-28334600-874a-11ea-925b-eb825c47e3e8.png)
and even an `Unavailable` item
![image](https://user-images.githubusercontent.com/4518597/80283451-35e8cb80-874a-11ea-9991-d74e9e8c331f.png)

**Comment by IX-Xur** [comment]
This should be fixed with the latest update.
