### ISSUE TITLE
Doesn't not work for Iceborne

### ISSUE THREAD

**Issue by JSLJ23** [IX-Xur/MHW-Shop-Editor#7]
Items in compiled .exe do show IB items, however when shopList.slt file is put in place, the game doesn't seem to recognize it and does not show the change.

**Comment by IX-Xur** [comment]
It's not supposed to work yet. Mod loading is broken right now, the only change was adding the names of the new items. When ready for use, there will be a release.

**Comment by JSLJ23** [comment]
Ok noted!
