### ISSUE TITLE
Button to save or copy & paste current list

### ISSUE THREAD

**Issue by JZharay** [IX-Xur/MHW-Shop-Editor#9]
Just a simple request that I have after playing with your editor. Since I want to make my own combo shoplist, it'd be great if I could copy the list I have and then paste it into another that I already have saved.

For example, I have a list of mostly end game monsters and GL parts. Now I want to fill in the remaining 30 slots with GL materials. I have the list, but no way to combine the two.

Good work so far. Don't stop what you're doing and keep adding to it!

**Comment by IX-Xur** [comment]
This is actually already possible! If both shop lists combined are under 255 items, you can load up one shop list and then open the second while the first is open. This will load the second list on top of the first one, combining the two. Then you can just save your new list.
